// example/pages/index.tsx
import type { NextPage } from "next"
import Head from "next/head"
import Link from "next/link"

const Index: NextPage = () => {
	return (
		<>
			<Head>
				<title>SpeakCaptcha Demo</title>
			</Head>
			<div className="mx-auto mt-12 max-w-screen-md p-12">
				<h1 className="my-4 text-center text-5xl font-bold">
					<strong className="font-black">Speak</strong>Captcha Demo
				</h1>
				<p className="mt-8 text-center text-xl">
					There are two ways you can integrate <strong>Speak</strong>Captcha into your
					application.
				</p>

				<div className="mt-12 flex flex-col items-center justify-center gap-4">
					<Link href="/with-events">
						<a className="text-lg text-blue-500">With Events</a>
					</Link>
					<Link href="/eventless">
						<a className="text-lg text-blue-500">Event-less</a>
					</Link>
				</div>

				<p className="mt-24 text-center text-gray-500">
					Both ways are perfectly fine to use. For more info, read the{" "}
					<a
						className="text-blue-500 underline"
						href={`${process.env.NEXT_PUBLIC_SPEAKCAPTCHA_URL}/developers/docs`}
					>
						documentation
					</a>
					.
				</p>
			</div>
		</>
	)
}

export default Index

// frontend/src/lib/pages/Index.svelte
<script lang="ts">
import { Link } from "svelte-navigator"
</script>

<div class="px-8">
	<h1 class="text-center text-5xl font-bold mt-16 mb-6">
		<strong class="font-black">Speak</strong>Captcha
	</h1>
	<p class="my-4 text-center text-2xl">The captcha that works by speaking.</p>
	<p class="my-4 text-center text-xl">
		<strong>Speak</strong>Captcha makes users speak the captcha text to the computer
		instead of clicking images.
	</p>

	<p class="my-8 text-center flex items-center text-xl justify-center">
		<Link to="/developers" class="button">Get started</Link>
	</p>
</div>

<div class="bg-gray-200 p-8">
	<h2 class="text-center text-3xl font-bold mt-4 mb-4">Captcha like never before</h2>
	<p class="my-4 text-center text-xl">
		<strong>Speak</strong>Captcha uses your microphone to make you complete the captcha.
		This makes it easier for you to complete captchas while still keeping bots away.
	</p>
	<p class="mt-8 mb-4 text-center flex items-center text-xl justify-center">
		<Link to="/developers" class="button">Try it now</Link>
	</p>
</div>

<div class="bg-white p-8">
	<h2 class="text-center text-3xl font-bold mt-4 mb-4">Accessible to everyone</h2>
	<p class="my-4 text-center text-xl">
		If you are visually impaired or can't complete the captcha due to other reasons, you
		can apply for an accessibility pass.
	</p>
	<p class="mt-8 mb-4 text-center flex items-center text-xl justify-center">
		<Link to="/accessibility" class="button">Apply for a pass</Link>
	</p>
</div>

<div class="bg-gray-200 p-8">
	<h2 class="text-center text-3xl font-bold mt-4 mb-4">Made for developers</h2>
	<p class="my-4 text-center text-xl">
		<strong>Speak</strong>Captcha is made with developers in mind. It is very easy to
		integrate <strong>Speak</strong>Captcha in your web application. Read the docs to
		get started.
	</p>
	<p class="mt-8 mb-4 text-center flex items-center gap-2 text-xl justify-center">
		<Link to="/documentation" class="button">Read the docs</Link>
		<a
			href="https://examples.speakcaptcha.gq"
			class="button !bg-white !hover:bg-gray-200 !focus:bg-gray-200 !text-blue-500"
			>View examples</a>
	</p>
</div>
